name: persons
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  # https://pub.dev/packages/drift
  drift: ^2.27.0
  # https://pub.dev/packages/drift_flutter
  drift_flutter: ^0.2.4
  # https://pub.dev/packages/meta
  meta: ^1.16.0
  # https://pub.dev/packages/path_provider
  path_provider: ^2.1.5
  # https://pub.dev/packages/logging
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0
  # https://pub.dev/packages/build_runner
  build_runner: ^2.5.4
  # https://pub.dev/packages/drift_dev
  drift_dev: ^2.27.0

flutter:
  generate: true
  uses-material-design: true
  # assets:
  #   - assets/