name: app
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/intl
  intl: ^0.20.2
  # https://pub.dev/packages/ansicolor
  ansicolor: ^2.0.3
  # https://pub.dev/packages/logging
  logging: ^1.3.0
  # https://pub.dev/packages/auto_route
  auto_route: ^10.1.0+1
  # https://pub.dev/packages/provider
  provider: ^6.1.5
  # https://pub.dev/packages/get_it
  get_it: ^8.2.0
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.5.3
  # https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.4.6
  # https://pub.dev/packages/rxdart
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0
  # https://pub.dev/packages/build_runner
  build_runner: ^2.4.2
  # https://pub.dev/packages/auto_route_generator
  auto_route_generator: ^10.2.3
  # https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  # assets:
  #   - assets/